# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6ffdf9c6928721ef218bdc8efc89f4405d16f078133c7c86d9996525639702a964569996ba8377bb3d2c46c337051930f37dd50ed5eae29cebcc1dc0495664

test:
  secret_key_base: 21612164c0a49353aeb222c668c6e1d0472ff49edb2605dd8d1bc373f128d2f3541fd1637faf693f84c2272aab1ef8c59c4f53d4b21d5fdabd62d12290becd42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
